# Generated by Terraform module veil_compose — do not edit by hand.
COMPOSE_PROJECT_NAME=${project_name}
PIPELINE_WORKER_SCALE=${pipeline_worker_scale}
INGEST_WORKER_SCALE=${ingest_worker_scale}
GRAPH_PACK_SKIP=${graph_pack_skip}
VEIL_PROFILE=${profile}
VEIL_PROFILE_PATH=${profile_path}
