#!/usr/bin/env bash
# Sync graph consumer copy of ingestv1 from pipeline canonical package.
# scrapev1 is maintained in scrape/contract/scrapev1 (not overwritten here).
# Run from repository root: ./scripts/gen-contracts.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GEN_HEADER='// Code generated by scripts/gen-contracts.sh; DO NOT EDIT.
// Source of truth: docs/schemas/ingestv1-envelope.json — copied from pipeline/contract/ingestv1.

'

copy_ingest_to_graph() {
  local src_pkg="$1"
  local dst_dir="$2"
  mkdir -p "$dst_dir"
  for f in "$src_pkg"/*.go; do
    [[ -f "$f" ]] || continue
    base=$(basename "$f")
    [[ "$base" == *_test.go ]] && continue
    {
      printf '%s' "$GEN_HEADER"
      sed 's|github.com/butbeautifulv/threat_intelligence/pipeline/contract/ingestv1|github.com/butbeautifulv/threat_intelligence/graph/contract/ingestv1|g' "$f"
    } > "$dst_dir/$base"
  done
}

INGEST_SRC="$ROOT/pipeline/contract/ingestv1"
if [[ ! -f "$INGEST_SRC/envelope.go" ]] || ! grep -q 'func NewEnvelope' "$INGEST_SRC/envelope.go" 2>/dev/null; then
  echo "gen-contracts: missing pipeline/contract/ingestv1/envelope.go" >&2
  exit 1
fi

copy_ingest_to_graph "$INGEST_SRC" "$ROOT/graph/contract/ingestv1"
cat > "$ROOT/graph/contract/ingestv1/go.mod" <<'EOF'
module github.com/butbeautifulv/threat_intelligence/graph/contract/ingestv1

go 1.25.0
EOF

echo "gen-contracts: OK (graph/contract/ingestv1 synced from pipeline/contract/ingestv1)"
